DELETE FROM mno_id_map;
DELETE FROM llx_paiement_facture;
DELETE FROM llx_facturedet;
DELETE FROM llx_facture;
DELETE FROM llx_socpeople;
DELETE FROM llx_societe;
DELETE FROM llx_product_price;
DELETE FROM llx_product_fournisseur_price;
DELETE FROM llx_product;
DELETE FROM llx_bank;
DELETE FROM llx_bank_account;
DELETE FROM llx_c_tva WHERE rowid >= 2469;
DELETE FROM llx_paiement;
DELETE FROM llx_paiement_facture;
DELETE FROM llx_user_rights;
DELETE FROM llx_user;
